# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sort_name_te = QtWidgets.QLineEdit(Form)
        self.sort_name_te.setObjectName("sort_name_te")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sort_name_te)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.roasting_te = QtWidgets.QLineEdit(Form)
        self.roasting_te.setObjectName("roasting_te")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roasting_te)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ground_cb = QtWidgets.QComboBox(Form)
        self.ground_cb.setObjectName("ground_cb")
        self.ground_cb.addItem("")
        self.ground_cb.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground_cb)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.description_pte = QtWidgets.QPlainTextEdit(Form)
        self.description_pte.setObjectName("description_pte")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.description_pte)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.price_sb = QtWidgets.QSpinBox(Form)
        self.price_sb.setMaximum(1000000)
        self.price_sb.setSingleStep(50)
        self.price_sb.setProperty("value", 100)
        self.price_sb.setObjectName("price_sb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price_sb)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.volume_sb = QtWidgets.QSpinBox(Form)
        self.volume_sb.setMaximum(10000)
        self.volume_sb.setSingleStep(50)
        self.volume_sb.setProperty("value", 250)
        self.volume_sb.setObjectName("volume_sb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume_sb)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.save_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменить информацию"))
        self.label.setText(_translate("Form", "Название сорта"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Молотый/в зернах"))
        self.ground_cb.setItemText(0, _translate("Form", "Молотый"))
        self.ground_cb.setItemText(1, _translate("Form", "В зернах"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объем упаковки"))
        self.save_btn.setText(_translate("Form", "Добавить"))
